### ISSUE TITLE
Investigate lodash modularized utilities

### ISSUE THREAD

**Issue by rawls238** [rawls238/PlanOut.js#39]
@chrisvoll pointed out that we could replace a lot of the functions in the [utils file](https://github.com/HubSpot/PlanOut.js/blob/master/es6/lib/utils.js with) with [lodash modularized utilities](https://www.npmjs.com/browse/keyword/lodash-modularized). The whole point of the utils file is to reduce the bundle size by not having to pull in underscore/lodash since we only require a small subset of the functions supplied. 

Switching to lodash modularized utilities basically gives us that as well as hopefully making this library more future proof since those utility libraries will adapt as javascript/browser implementations change whereas the local utils file here likely will not. I also wonder if it will give us any further reductions in bundle size, though I'm not sure how big this reduction will be (or if there will even be one).

**Comment by alexindigo** [comment]
I agree it would be beneficial for all parties to adopt more Javascripty way and split it into / reuse npm modules.

For example Random operation could be it's own npm module, allowing community to benefit from it in more ways.

Thank you.
