### ISSUE TITLE
.babelrc interferes with building

### ISSUE THREAD

**Issue by redmagic** [rawls238/PlanOut.js#46]
When using `import PlanOut from 'planout';` and building with babel/webpack, babel tries to resolve the presets and plugins from Planout's `.babelrc`.

Since we are importing the transpiled code, this should not happen. While this can be circumvented using `babelrc: false` and extending to the parent project's `.babelrc`, it might be better to add the `.babelrc` to the command line used when testing the package.

**Comment by rawls238** [comment]
good catch, feel free to PR the fix!
