### ISSUE TITLE
"bower install planout" errors

### ISSUE THREAD

**Issue by burkhartt** [rawls238/PlanOut.js#49]
> bower install planout                                             0 < 17:14:15
bower cached        https://github.com/HubSpot/PlanOut.js.git#3.0.1
bower validate      3.0.1 against https://github.com/HubSpot/PlanOut.js.git#*
bower cached        https://github.com/MikeMcl/bignumber.js.git#2.0.7
bower validate      2.0.7 against https://github.com/MikeMcl/bignumber.js.git#2.0.7
bower ENOTFOUND     Package sha1 not found

**Comment by rawls238** [comment]
@mattrheault I'm not actually sure I actually published this properly on bower...would be great if you could figure out how to do that

**Comment by rawls238** [comment]
from now on, only npm will contain the latest version.
