### ISSUE TITLE
Allow an experiment (not just a namespace) to be locally overridden

### ISSUE THREAD

**Issue by joshuatTW** [rawls238/PlanOut.js#67]
If I'm correct, only namespaces can be locally overridden. It would be nice to be able to test a single experiment locally.

**Comment by rawls238** [comment]
I agree that that sounds like something reasonable that should be doable with the library. I’ll think about the best way to implement this this weekend

**Comment by jorilallo** [comment]
@rawls238 finally jumping into using Planout.js and also ran into this issue (and banged my head against the wall as it wasn't documented a bit).

**Comment by rawls238** [comment]
ah sorry, definitely should have been better documented. However, this should be easy to implement...hopefully will find some time this week to add this functionality.

**Comment by scottfr** [comment]
It would be great to have this feature implemented.

**Comment by rawls238** [comment]
this has been implemented thanks to @niklasnordlund!
