### ISSUE TITLE
Calculation of random integer needs a fix ?

### ISSUE THREAD

**Issue by alok87** [rawls238/PlanOut.js#76]
https://github.com/HubSpot/PlanOut.js/blob/2e917673fc47146c09a4b040188b0cc7479cc203/es6/ops/randomPlanoutCoreCompatible.js#L25-L29

## Test case where it is failing
Min Value = 7
Max Value = 20
getHash() = 108
Result = 108.plus(7).modulo(20 - 7 + 1) = 115 % 14 = 3

Issue: 3 is not in range between 7 and 20

The formula will not work if the min > 0. 

Should  not the formula be 
`return this.getHash().modulo(maxVal - minVal + 1).plus(minVal).toNumber();`
instead of 
 `return this.getHash().plus(minVal).modulo(maxVal - minVal + 1).toNumber();`

cc @anuragagarwal561994 @devenvyas

**Comment by rawls238** [comment]
Thanks, yes this seems like a bug. Can you put up a PR with the fix as well as some tests?

**Comment by rawls238** [comment]
fixed in  #78
