### ISSUE TITLE
default import stopped working with upgrade to v5

### ISSUE THREAD

**Issue by tmcdonnell87** [rawls238/PlanOut.js#81]
Code:
```
import PlanOut from 'planout';

export default class BaseExperiment extends PlanOut.Experiment {
...
}
```
Error is that PlanOut is undefined. Now that it is exported as a module, everything must be imported as something like `import { Experiment } from 'planout'`. 

This is a breaking change; if intentional, it should be called out in the ReadMe. 

Thanks for your work maintaining this!

**Comment by rawls238** [comment]
yes this came about as a result of the 4.0 change, which apparently had not been pushed to npm. Sorry about this. I will make it explicit in the change log and README.

**Comment by glifchits** [comment]
```javascript 
import * as PlanOut from "planout";
```
is a workaround which makes code behave just like it did before.

@rawls238 I'm not sure whether you've updated the README yet, but the main example on the README is out-of-date / incorrect.

Also, thanks for maintaining this library! 😄

**Comment by rawls238** [comment]
@glifchits good catch! I will update it

**Comment by rawls238** [comment]
@glifchits I have updated the README to reflect this. I'll close the issue now since that this has been directly addressed in the README now.
