### ISSUE TITLE
are types missing in the npm package?

### ISSUE THREAD

**Issue by gilm123** [rawls238/PlanOut.js#86]
hii,
i'm writing in typescript and couldn't find anywhere in the installed the package the d.ts i saw was recently added

**Comment by rammie** [comment]
Hello, thanks for this awesome package! Can we get a new npm package with the types when you have some time? Thanks!

**Comment by rawls238** [comment]
thanks for reminding me! Will update on NPM sometime this week

**Comment by rawls238** [comment]
Latest version is updated and publish as planout@5.1.0. Let me know if there are any issues!
