### ISSUE TITLE
Need to understand the significance of second parameter of get()

### ISSUE THREAD

**Issue by karmasakshi** [rawls238/PlanOut.js#92]
https://github.com/rawls238/PlanOut.js/blob/86470825da681b45598894db38b550d4a645daa8/types/index.d.ts#L194

When I say `experiment.get(param)` I get the error that `get()` expects two parameters. What is the value expected here?

**Comment by rawls238** [comment]
It is the default value.

**Comment by karmasakshi** [comment]
I thought so too. Maybe I don't fully understand when this value will be used. Will the default value be returned if I pass an empty choices array?

If you'd like to have a look at my code, here's a service that returns a configuration to a user. https://github.com/karmasakshi/planout-store/blob/main/apps/api/src/app/configuration/configuration.service.ts

... and here's the PlanOut class:
https://github.com/karmasakshi/planout-store/blob/20737e9e55b50d1e6e2630823172b4f48f697d1b/apps/api/src/app/experiment.ts#L4

**Comment by karmasakshi** [comment]
I noticed the default value when I didn't pass the param. Thanks for your input.
